#include <iostream>
using namespace std;

int main() {
    int n;
    cin >> n;

    if (n == 1) cout << "One";
    else if (n == 2) cout << "Two";
    else if (n == 3) cout << "Three";
    else if (n == 4) cout << "Four";
    else if (n == 5) cout << "Five";
    else if (n == 6) cout << "Six";
    else if (n == 7) cout << "Seven";
    else if (n == 8) cout << "Eight";
    else if (n == 9) cout << "Nine";
    else if (n == 10) cout << "Ten";
    else if (n == 11) cout << "Eleven";
    else if (n == 12) cout << "Twelve";
    else if (n == 13) cout << "Thirteen";
    else if (n == 14) cout << "Fourteen";
    else if (n == 15) cout << "Fifteen";
    else if (n == 16) cout << "Sixteen";
    else if (n == 17) cout << "Seventeen";
    else if (n == 18) cout << "Eighteen";
    else if (n == 19) cout << "Nineteen";
    else if (n == 20) cout << "Twenty";
    else if (n == 21) cout << "Twenty-One";
    else if (n == 22) cout << "Twenty-Two";
    else if (n == 23) cout << "Twenty-Three";
    else if (n == 24) cout << "Twenty-Four";
    else if (n == 25) cout << "Twenty-Five";
    else if (n == 26) cout << "Twenty-Six";
    else if (n == 27) cout << "Twenty-Seven";
    else if (n == 28) cout << "Twenty-Eight";
    else if (n == 29) cout << "Twenty-Nine";
    else if (n == 30) cout << "Thirty";
    else if (n == 31) cout << "Thirty-One";
    else if (n == 32) cout << "Thirty-Two";
    else if (n == 33) cout << "Thirty-Three";
    else if (n == 34) cout << "Thirty-Four";
    else if (n == 35) cout << "Thirty-Five";
    else if (n == 36) cout << "Thirty-Six";
    else if (n == 37) cout << "Thirty-Seven";
    else if (n == 38) cout << "Thirty-Eight";
    else if (n == 39) cout << "Thirty-Nine";
    else if (n == 40) cout << "Forty";
    else if (n == 41) cout << "Forty-One";
    else if (n == 42) cout << "Forty-Two";
    else if (n == 43) cout << "Forty-Three";
    else if (n == 44) cout << "Forty-Four";
    else if (n == 45) cout << "Forty-Five";
    else if (n == 46) cout << "Forty-Six";
    else if (n == 47) cout << "Forty-Seven";
    else if (n == 48) cout << "Forty-Eight";
    else if (n == 49) cout << "Forty-Nine";
    else if (n == 50) cout << "Fifty";
    else if (n == 51) cout << "Fifty-One";
    else if (n == 52) cout << "Fifty-Two";
    else if (n == 53) cout << "Fifty-Three";
    else if (n == 54) cout << "Fifty-Four";
    else if (n == 55) cout << "Fifty-Five";
    else if (n == 56) cout << "Fifty-Six";
    else if (n == 57) cout << "Fifty-Seven";
    else if (n == 58) cout << "Fifty-Eight";
    else if (n == 59) cout << "Fifty-Nine";
    else if (n == 60) cout << "Sixty";
    else if (n == 61) cout << "Sixty-One";
    else if (n == 62) cout << "Sixty-Two";
    else if (n == 63) cout << "Sixty-Three";
    else if (n == 64) cout << "Sixty-Four";
    else if (n == 65) cout << "Sixty-Five";
    else if (n == 66) cout << "Sixty-Six";
    else if (n == 67) cout << "Sixty-Seven";
    else if (n == 68) cout << "Sixty-Eight";
    else if (n == 69) cout << "Sixty-Nine";
    else if (n == 70) cout << "Seventy";
    else if (n == 71) cout << "Seventy-One";
    else if (n == 72) cout << "Seventy-Two";
    else if (n == 73) cout << "Seventy-Three";
    else if (n == 74) cout << "Seventy-Four";
    else if (n == 75) cout << "Seventy-Five";
    else if (n == 76) cout << "Seventy-Six";
    else if (n == 77) cout << "Seventy-Seven";
    else if (n == 78) cout << "Seventy-Eight";
    else if (n == 79) cout << "Seventy-Nine";
    else if (n == 80) cout << "Eighty";
    else if (n == 81) cout << "Eighty-One";
    else if (n == 82) cout << "Eighty-Two";
    else if (n == 83) cout << "Eighty-Three";
    else if (n == 84) cout << "Eighty-Four";
    else if (n == 85) cout << "Eighty-Five";
    else if (n == 86) cout << "Eighty-Six";
    else if (n == 87) cout << "Eighty-Seven";
    else if (n == 88) cout << "Eighty-Eight";
    else if (n == 89) cout << "Eighty-Nine";
    else if (n == 90) cout << "Ninety";
    else if (n == 91) cout << "Ninety-One";
    else if (n == 92) cout << "Ninety-Two";
    else if (n == 93) cout << "Ninety-Three";
    else if (n == 94) cout << "Ninety-Four";
    else if (n == 95) cout << "Ninety-Five";
    else if (n == 96) cout << "Ninety-Six";
    else if (n == 97) cout << "Ninety-Seven";
    else if (n == 98) cout << "Ninety-Eight";
    else if (n == 99) cout << "Ninety-Nine";
    else cout << "Number out of range";

    return 0;
}
